### ISSUE TITLE
Apply your code on a new corpus

### ISSUE THREAD

**Issue by tienduccao** [valdersoul/GraphBTM#2]
I couldn't find instruction to generate the following files for a new corpus.
```test.txt.npy, train.txt.npy, valid.txt.npy, vocab.pkl```
Regarding the new corpus, would it be sufficient if I supply the text its text in ```data/20news_clean/corpus.txt```?

**Comment by valdersoul** [comment]
No, you also need to extract the vocabulary from the text and transform the tokens into the indexes in the vocabulary file.

**Comment by tienduccao** [comment]
Could you provide an example regarding these files ``test.txt.npy, train.txt.npy, valid.txt.npy``?

**Comment by valdersoul** [comment]
For example, the vocab dictionary is like below:
{'apple' : 0,
 'I': 1,
 "have"; 2.
  'an': 3,
  "you': 4
}

Then the representation of a document 'I have an apple' will be 1 2 3 0 in the corresponding npy file.

**Comment by tienduccao** [comment]
Thanks.
