### ISSUE TITLE
inference topic distribution probability for a document

### ISSUE THREAD

**Issue by jingcheng-du** [valdersoul/GraphBTM#3]
Hi, thank you for sharing the code. I was wondering how can we infer topic document distribution probability from the word topic distribution probability generated by Graph-BTM?

**Comment by valdersoul** [comment]
Hi jingcheng, the topic distribution can be inferred from the latent code z, in which you can apply the softmax on the mean part of the posterior.

**Comment by jingcheng-du** [comment]
thanks for your timely reply!

**Comment by jingcheng-du** [comment]
Hi, it seems that the training was based on the biterms from a mini-corpus. for prediction (infer topics for a document), how should we generate the biterms, the biterms from that specific document only?

**Comment by valdersoul** [comment]
Hi, you can set the mini-corpus to 1 and then the document is only using it.
